# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{xpcomcore-rubygem}
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["ggironda"]
  s.date = %q{2009-10-07}
  s.description = %q{Gem to allow for using XPCOMCore via RubyGems}
  s.email = %q{gabriel.gironda@gmail.com}
  s.executables = ["xpcomcore-rubygem-install", "xpcomcore-firefox"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/xpcomcore-firefox",
     "bin/xpcomcore-rubygem-install",
     "extension/README.txt",
     "extension/components/bootstrapper.js",
     "extension/install.rdf",
     "lib/xpcomcore-rubygem.rb",
     "test/test_helper.rb",
     "test/xpcomcore-rubygem_test.rb",
     "xpcomcore-rubygem.gemspec"
  ]
  s.homepage = %q{http://github.com/gabrielg/xpcomcore-rubygem}
  s.post_install_message = %q{
[1m[31m[44m                                                                                [0m[0m
[1m[31m[44m                       PAY HEED TO THIS ANNOYING MESSAGE                        [0m[0m
[1m[31m[44m                                                                                [0m[0m

The XPCOMCore gem has been installed but you still need to complete installation
by hand. Run the command [1m[4mxpcomcore-rubygem-install[0m[0m without options to get
usage information on using it to install the bootstrapper code for this gem.

}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Gem to allow for using XPCOMCore via RubyGems}
  s.test_files = [
    "test/test_helper.rb",
     "test/xpcomcore-rubygem_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sys-uname>, [">= 0"])
      s.add_development_dependency(%q<colored>, [">= 0"])
    else
      s.add_dependency(%q<sys-uname>, [">= 0"])
      s.add_dependency(%q<colored>, [">= 0"])
    end
  else
    s.add_dependency(%q<sys-uname>, [">= 0"])
    s.add_dependency(%q<colored>, [">= 0"])
  end
end
